import { access, copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { basename, extname, isAbsolute, relative, resolve } from "node:path";

const clientRoot = resolve(import.meta.dirname, "..");
const projectRoot = resolve(clientRoot, "..");
const drawableRoot = resolve(clientRoot, "app", "src", "main", "res", "drawable");

const required = (name) => {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`Missing required build parameter: ${name}`);
  return value;
};

const escapeProperty = (value) => value.replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/\r/g, "\\r");
const normalizeApiBaseUrl = (value) => {
  const withScheme = /^https:\/\//i.test(value) ? value : `https://${value}`;
  const url = new URL(withScheme);
  if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/" || url.search || url.hash) {
    throw new Error("CLIENT_COMMUNICATION_DOMAIN must be an HTTPS domain without a path, credentials, query, or fragment.");
  }
  return `${url.origin}/api/v1`;
};

const communicationDomain = required("CLIENT_COMMUNICATION_DOMAIN");
const communicationKey = required("CLIENT_COMMUNICATION_KEY");
const displayName = required("CLIENT_DISPLAY_NAME");
const versionName = required("CLIENT_VERSION_NAME");
const applicationId = required("CLIENT_APPLICATION_ID");
const keystoreFile = required("CLIENT_KEYSTORE_FILE");
const keystorePassword = required("CLIENT_KEYSTORE_PASSWORD");
const keyAlias = required("CLIENT_KEY_ALIAS");
const keyPassword = required("CLIENT_KEY_PASSWORD");

if (!/^(?:0|[1-9][0-9]{0,2})\.(?:0|[1-9][0-9]{0,2})\.(?:0|[1-9][0-9]{0,2})$/.test(versionName)) {
  throw new Error("CLIENT_VERSION_NAME must use major.minor.patch semantic versioning.");
}
if (!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(applicationId)) throw new Error("CLIENT_APPLICATION_ID must be a valid lowercase Android package name.");
if (applicationId.length > 60) throw new Error("CLIENT_APPLICATION_ID is too long for the native OIDC redirect scheme.");
if (!/^[A-Za-z0-9_-]{43}$/.test(communicationKey)) throw new Error("CLIENT_COMMUNICATION_KEY must be a 32-byte URL-safe key generated by HL6.");
if (displayName.length > 80 || /[\u0000-\u001F\u007F]/.test(displayName)) throw new Error("CLIENT_DISPLAY_NAME must be at most 80 printable characters.");

const versionParts = (versionName.match(/\d+/g) ?? []).slice(0, 3).map(Number);
const versionCode = Math.max(1, (versionParts[0] ?? 0) * 1_000_000 + (versionParts[1] ?? 0) * 1_000 + (versionParts[2] ?? 0));
const properties = {
  "client.applicationId": applicationId,
  "client.versionCode": String(versionCode),
  "client.versionName": versionName,
  "client.displayName": displayName,
  "client.apiBaseUrl": normalizeApiBaseUrl(communicationDomain),
  "client.communicationKey": communicationKey,
  "client.nativeRedirectUri": `hl6.${applicationId}://auth/callback`,
  "client.keystoreFile": keystoreFile,
  "client.keystorePassword": keystorePassword,
  "client.keyAlias": keyAlias,
  "client.keyPassword": keyPassword,
};

await writeFile(
  resolve(clientRoot, "local.properties"),
  `${Object.entries(properties).map(([key, value]) => `${key}=${escapeProperty(value)}`).join("\n")}\n`,
  "utf8",
);

const iconInput = process.env.CLIENT_ICON_PATH?.trim();
await rm(resolve(drawableRoot, "client_icon.png"), { force: true });
await copyFile(resolve(drawableRoot, "client_icon_default.xml"), resolve(drawableRoot, "client_icon.xml"));
if (iconInput) {
  const source = resolve(projectRoot, iconInput);
  const relativeSource = relative(projectRoot, source);
  if (relativeSource.startsWith("..") || isAbsolute(relativeSource) || extname(source).toLowerCase() !== ".png") {
    throw new Error("CLIENT_ICON_PATH must be a repository-relative PNG path.");
  }
  try {
    await access(source);
  } catch {
    throw new Error("CLIENT_ICON_PATH does not reference a readable repository PNG file.");
  }
  await mkdir(drawableRoot, { recursive: true });
  await rm(resolve(drawableRoot, "client_icon.xml"), { force: true });
  await copyFile(source, resolve(drawableRoot, "client_icon.png"));
  console.log(`Applied native Android icon from ${basename(source)}.`);
}

console.log(`Configured native Android build: ${applicationId} ${versionName} (${versionCode}).`);
