stages:
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

variables:
  http_proxy: "http://192.168.6.35:7890"
  https_proxy: "http://192.168.6.35:7890"
  HTTP_PROXY: "http://192.168.6.35:7890"
  HTTPS_PROXY: "http://192.168.6.35:7890"

app:docker:
  stage: build
  image:
    name: c852603567b1aa7e9615cb023b134046.d.1ms.run/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/app"
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - .dockerignore
        - Dockerfile
        - server/**/*
        - web/**/*
    - when: never
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - export IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - export DESTINATIONS="--destination ${IMAGE_NAME}:${IMAGE_TAG}"
    - >
      if [ "${CI_COMMIT_BRANCH}" = "main" ] && [ -z "${CI_COMMIT_TAG}" ]; then
        DESTINATIONS="${DESTINATIONS} --destination ${IMAGE_NAME}:latest";
      fi
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg HTTP_PROXY="${HTTP_PROXY}"
      --build-arg HTTPS_PROXY="${HTTPS_PROXY}"
      --build-arg http_proxy="${http_proxy}"
      --build-arg https_proxy="${https_proxy}"
      ${DESTINATIONS}

pages:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never
  script:
    - rm -rf public
    - mkdir -p public
    - |
      cat > public/_redirects <<'EOF'
      /* https://domain.houlang.cloud/:splat 301
      EOF
  artifacts:
    paths:
      - public
    expire_in: 30 days
