include:
  - project: 'houlangcloud/templates'
    ref: 'main'
    file: '/kaniko.yml'

stages:
  - build

app:docker:
  extends: .kaniko:build
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/app"
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - .dockerignore
        - Dockerfile
        - server/**/*
        - web/**/*
    - when: never

pages:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - web/**/*
    - when: never
  script:
    - rm -rf public
    - mkdir -p public
    - |
      cat > public/_redirects <<'EOF'
      /* https://domain.houlang.cloud/:splat 301
      EOF
  artifacts:
    paths:
      - public
    expire_in: 30 days
