include:
  - project: 'houlangcloud/templates'
    ref: 'main'
    file: '/kaniko.yml'

stages:
  - build

app:docker:
  extends: .kaniko:build
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/app"
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - .dockerignore
        - Dockerfile
        - server/**/*
        - web/**/*
    - when: never