package migration

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"hl6-server/internal/auth"
	"hl6-server/internal/model"
	"hl6-server/internal/service"
)

const authCutoverAdvisoryLockKey int64 = 19490334

const (
	PreflightBlockerBlankLegacyEmail         = "blank_legacy_email"
	PreflightBlockerInvalidLegacyEmail       = "invalid_legacy_email"
	PreflightBlockerDuplicateNormalizedEmail = "duplicate_normalized_email"
	PreflightBlockerMissingDefaultGroup      = "missing_default_group"
	PreflightBlockerSMTPNotConfigured        = "smtp_not_configured"
	PreflightBlockerSMTPNotTested            = "smtp_not_tested"
	PreflightBlockerMissingPublicFrontendURL = "missing_public_frontend_url"
	PreflightBlockerNoVerifiedBackup         = "no_verified_backup"
	PreflightBlockerLocalAuthAlreadyEnabled  = "local_auth_already_enabled"
)

var (
	ErrConfirmationRequired   = errors.New("authentication cutover requires --confirm")
	ErrPreflightBlocked       = errors.New("authentication cutover preflight is blocked")
	ErrVerifiedBackupRequired = errors.New("authentication cutover requires a verified backup")
)

var safeSQLIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// AuthPreflightReport is safe to print in deployment logs. It deliberately
// reports counts and condition names only, never passwords, tokens, or SMTP
// credentials.
type AuthPreflightReport struct {
	Blockers                      []string `json:"blockers"`
	LegacyUserCount               int64    `json:"legacy_user_count"`
	BlankLegacyEmailCount         int64    `json:"blank_legacy_email_count"`
	InvalidLegacyEmailCount       int64    `json:"invalid_legacy_email_count"`
	DuplicateNormalizedEmailCount int64    `json:"duplicate_normalized_email_count"`
	DefaultGroupPresent           bool     `json:"default_group_present"`
	SMTPConfigured                bool     `json:"smtp_configured"`
	SMTPRecentlyTested            bool     `json:"smtp_recently_tested"`
	PublicFrontendURLConfigured   bool     `json:"public_frontend_url_configured"`
	ReadyBackupCount              int64    `json:"ready_backup_count"`
	LocalAuthEnabled              bool     `json:"local_auth_enabled"`
}

// AuthCutoverOptions separates the irreversible confirmation from the backup
// identifier. A backup record must have been generated by the server and its
// archive must still be present before legacy external-authentication data is removed.
type AuthCutoverOptions struct {
	Confirmed          bool
	BackupID           uint
	PublicFrontendURLs []string
}

// AuthPreflightOptions carries deployment-owned values that are intentionally
// never copied into SystemConfig. It keeps preflight usable when a production
// public URL is supplied solely through FRONTEND_URL.
type AuthPreflightOptions struct {
	PublicFrontendURLs []string
}

// AuthCutoverReport records the durable results of a successful hard cutover.
type AuthCutoverReport struct {
	BackupID                     uint  `json:"backup_id"`
	LegacyUsersProcessed         int64 `json:"legacy_users_processed"`
	ActivationCredentialsCreated int64 `json:"activation_credentials_created"`
}

// AuthPreflight checks whether an existing v1 installation can safely move to
// local credentials. It does not mutate business data.
func AuthPreflight(ctx context.Context, db *gorm.DB) (AuthPreflightReport, error) {
	return AuthPreflightWithOptions(ctx, db, AuthPreflightOptions{})
}

// AuthPreflightWithOptions checks whether an existing v1 installation can
// safely move to local credentials using both persistent settings and the
// deployment's configured public frontend URLs.
func AuthPreflightWithOptions(ctx context.Context, db *gorm.DB, options AuthPreflightOptions) (AuthPreflightReport, error) {
	if db == nil {
		return AuthPreflightReport{}, errors.New("auth preflight database is nil")
	}

	report := AuthPreflightReport{}
	var users []model.User
	if err := db.WithContext(ctx).Find(&users).Error; err != nil {
		return report, fmt.Errorf("load legacy users: %w", err)
	}
	report.LegacyUserCount = int64(len(users))
	normalizedCounts := make(map[string]int)
	for _, user := range users {
		email := strings.TrimSpace(user.Email)
		if email == "" {
			report.BlankLegacyEmailCount++
			continue
		}
		normalized, err := auth.NormalizeEmail(email)
		if err != nil {
			report.InvalidLegacyEmailCount++
			continue
		}
		normalizedCounts[normalized]++
	}
	for _, count := range normalizedCounts {
		if count > 1 {
			report.DuplicateNormalizedEmailCount += int64(count)
		}
	}
	if report.BlankLegacyEmailCount > 0 {
		report.Blockers = append(report.Blockers, PreflightBlockerBlankLegacyEmail)
	}
	if report.InvalidLegacyEmailCount > 0 {
		report.Blockers = append(report.Blockers, PreflightBlockerInvalidLegacyEmail)
	}
	if report.DuplicateNormalizedEmailCount > 0 {
		report.Blockers = append(report.Blockers, PreflightBlockerDuplicateNormalizedEmail)
	}

	var defaultGroupCount int64
	if err := db.WithContext(ctx).Model(&model.UserGroup{}).Where("is_default = ?", true).Count(&defaultGroupCount).Error; err != nil {
		return report, fmt.Errorf("check default group: %w", err)
	}
	report.DefaultGroupPresent = defaultGroupCount == 1
	if !report.DefaultGroupPresent {
		report.Blockers = append(report.Blockers, PreflightBlockerMissingDefaultGroup)
	}

	configs, err := authPreflightConfigs(ctx, db)
	if err != nil {
		return report, err
	}
	report.SMTPConfigured = configs["smtp_enabled"] == "true" && strings.TrimSpace(configs["smtp_host"]) != "" && strings.TrimSpace(configs["smtp_from_addr"]) != ""
	if !report.SMTPConfigured {
		report.Blockers = append(report.Blockers, PreflightBlockerSMTPNotConfigured)
	}
	if testedAt, parseErr := time.Parse(time.RFC3339, strings.TrimSpace(configs["email.smtp.last_tested_at"])); parseErr == nil && testedAt.After(time.Now().UTC().Add(-30*24*time.Hour)) {
		report.SMTPRecentlyTested = true
	}
	if !report.SMTPRecentlyTested {
		report.Blockers = append(report.Blockers, PreflightBlockerSMTPNotTested)
	}
	report.PublicFrontendURLConfigured = hasHTTPSPublicURL(configs["frontend_urls"]) || hasHTTPSPublicURL(configs["frontend_url"])
	if !report.PublicFrontendURLConfigured {
		for _, candidate := range options.PublicFrontendURLs {
			if hasHTTPSPublicURL(candidate) {
				report.PublicFrontendURLConfigured = true
				break
			}
		}
	}
	if !report.PublicFrontendURLConfigured {
		report.Blockers = append(report.Blockers, PreflightBlockerMissingPublicFrontendURL)
	}
	report.LocalAuthEnabled = configs["auth.local.enabled"] == "true"
	if report.LocalAuthEnabled {
		report.Blockers = append(report.Blockers, PreflightBlockerLocalAuthAlreadyEnabled)
	}

	if err := db.WithContext(ctx).Model(&model.DatabaseBackup{}).
		Where("status = ? AND storage_path <> '' AND checksum_sha256 <> ''", model.DatabaseBackupStatusReady).
		Count(&report.ReadyBackupCount).Error; err != nil {
		return report, fmt.Errorf("check verified backups: %w", err)
	}
	if report.ReadyBackupCount == 0 {
		report.Blockers = append(report.Blockers, PreflightBlockerNoVerifiedBackup)
	}
	sort.Strings(report.Blockers)
	return report, nil
}

// AuthCutover replaces legacy external-identity data with activation-required
// local credentials. It is intentionally only callable from deployment code,
// never from an HTTP endpoint.
func AuthCutover(ctx context.Context, db *gorm.DB, options AuthCutoverOptions) (AuthCutoverReport, error) {
	if !options.Confirmed {
		return AuthCutoverReport{}, ErrConfirmationRequired
	}
	if options.BackupID == 0 {
		return AuthCutoverReport{}, ErrVerifiedBackupRequired
	}
	if db == nil {
		return AuthCutoverReport{}, errors.New("auth cutover database is nil")
	}

	var backup model.DatabaseBackup
	if err := db.WithContext(ctx).First(&backup, options.BackupID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return AuthCutoverReport{}, ErrVerifiedBackupRequired
		}
		return AuthCutoverReport{}, fmt.Errorf("load verified backup: %w", err)
	}
	if backup.Status != model.DatabaseBackupStatusReady || strings.TrimSpace(backup.StoragePath) == "" || strings.TrimSpace(backup.ChecksumSHA256) == "" {
		return AuthCutoverReport{}, ErrVerifiedBackupRequired
	}
	if err := service.VerifyBackupArchive(ctx, backup.StoragePath, backup.ChecksumSHA256); err != nil {
		return AuthCutoverReport{}, fmt.Errorf("%w: archive validation failed: %v", ErrVerifiedBackupRequired, err)
	}

	report, err := AuthPreflightWithOptions(ctx, db, AuthPreflightOptions{
		PublicFrontendURLs: options.PublicFrontendURLs,
	})
	if err != nil {
		return AuthCutoverReport{}, err
	}
	if len(report.Blockers) > 0 {
		return AuthCutoverReport{}, fmt.Errorf("%w: %s", ErrPreflightBlocked, strings.Join(report.Blockers, ","))
	}

	result := AuthCutoverReport{BackupID: backup.ID, LegacyUsersProcessed: report.LegacyUserCount}
	err = db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Exec("SELECT pg_advisory_xact_lock(?)", authCutoverAdvisoryLockKey).Error; err != nil {
			return fmt.Errorf("acquire auth cutover lock: %w", err)
		}
		if err := InstallAuthSchema(tx); err != nil {
			return fmt.Errorf("install auth schema: %w", err)
		}

		var users []model.User
		if err := tx.Find(&users).Error; err != nil {
			return fmt.Errorf("load users for cutover: %w", err)
		}
		now := time.Now().UTC()
		for _, user := range users {
			normalized, normalizeErr := auth.NormalizeEmail(user.Email)
			if normalizeErr != nil {
				return fmt.Errorf("normalize legacy user %d: %w", user.ID, normalizeErr)
			}
			credential := model.UserCredential{
				UserID:               user.ID,
				EmailNormalized:      normalized,
				PasswordHash:         "",
				PasswordHashVersion:  "",
				SessionVersion:       1,
				ActivationRequiredAt: &now,
			}
			resultWrite := tx.Clauses(clause.OnConflict{
				Columns: []clause.Column{{Name: "user_id"}},
				DoUpdates: clause.Assignments(map[string]interface{}{
					"email_normalized":       normalized,
					"password_hash":          "",
					"password_hash_version":  "",
					"email_verified_at":      nil,
					"password_set_at":        nil,
					"activation_required_at": &now,
					"session_version":        gorm.Expr(quotedIdentifier(tx.NamingStrategy.TableName("UserCredential")) + ".\"session_version\" + 1"),
				}),
			}).Create(&credential)
			if resultWrite.Error != nil {
				return fmt.Errorf("create activation credential for user %d: %w", user.ID, resultWrite.Error)
			}
			result.ActivationCredentialsCreated += resultWrite.RowsAffected
		}

		if err := removeLegacyIdentityObjects(tx); err != nil {
			return err
		}
		if err := tx.Where("\"key\" = ?", "auth.local.enabled").Delete(&model.SystemConfig{}).Error; err != nil {
			return fmt.Errorf("clear local authentication state: %w", err)
		}
		if err := tx.Create(&model.SystemConfig{Key: "auth.local.enabled", Value: "true"}).Error; err != nil {
			return fmt.Errorf("enable local authentication: %w", err)
		}
		if len(users) > 0 {
			details, marshalErr := json.Marshal(map[string]interface{}{
				"backup_id":                      backup.ID,
				"legacy_users_processed":         result.LegacyUsersProcessed,
				"activation_credentials_created": result.ActivationCredentialsCreated,
			})
			if marshalErr != nil {
				return fmt.Errorf("serialize cutover audit details: %w", marshalErr)
			}
			if err := tx.Create(&model.AuditLog{
				UserID:   users[0].ID,
				Action:   "auth_hard_cutover",
				Resource: "authentication",
				Details:  details,
			}).Error; err != nil {
				return fmt.Errorf("write auth cutover audit log: %w", err)
			}
		}
		return nil
	})
	if err != nil {
		return AuthCutoverReport{}, err
	}
	return result, nil
}

func authPreflightConfigs(ctx context.Context, db *gorm.DB) (map[string]string, error) {
	keys := []string{
		"smtp_enabled",
		"smtp_host",
		"smtp_from_addr",
		"email.smtp.last_tested_at",
		"frontend_urls",
		"frontend_url",
		"auth.local.enabled",
	}
	var configs []model.SystemConfig
	if err := db.WithContext(ctx).Where("\"key\" IN ?", keys).Find(&configs).Error; err != nil {
		return nil, fmt.Errorf("load authentication preflight configuration: %w", err)
	}
	result := make(map[string]string, len(configs))
	for _, cfg := range configs {
		result[cfg.Key] = strings.TrimSpace(cfg.Value)
	}
	return result, nil
}

func hasHTTPSPublicURL(raw string) bool {
	for _, candidate := range strings.FieldsFunc(raw, func(r rune) bool { return r == ',' || r == '\n' || r == '\r' }) {
		parsed, err := url.ParseRequestURI(strings.TrimSpace(candidate))
		if err == nil && parsed.Scheme == "https" && parsed.Host != "" {
			return true
		}
	}
	return false
}

func removeLegacyIdentityObjects(tx *gorm.DB) error {
	if err := tx.Where(`"key" LIKE ? ESCAPE '\'`, `oidc\_%`).Delete(&model.SystemConfig{}).Error; err != nil {
		return fmt.Errorf("remove legacy external-authentication settings: %w", err)
	}
	for _, modelName := range []string{"NativeAuthCode", "NativeAuthRequest"} {
		table := tx.NamingStrategy.TableName(modelName)
		if err := tx.Exec("DROP TABLE IF EXISTS " + quotedIdentifier(table)).Error; err != nil {
			return fmt.Errorf("drop legacy table %s: %w", table, err)
		}
	}
	usersTable := tx.NamingStrategy.TableName("User")
	hasExternalID, err := hasColumn(tx, usersTable, "external_id")
	if err != nil {
		return err
	}
	if hasExternalID {
		if err := tx.Exec("ALTER TABLE " + quotedIdentifier(usersTable) + " DROP COLUMN external_id").Error; err != nil {
			return fmt.Errorf("drop users.external_id: %w", err)
		}
	}
	return nil
}

func hasColumn(db *gorm.DB, table, column string) (bool, error) {
	var count int64
	err := db.Raw(`SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?`, table, column).Scan(&count).Error
	if err != nil {
		return false, fmt.Errorf("inspect %s.%s: %w", table, column, err)
	}
	return count > 0, nil
}

func quotedIdentifier(identifier string) string {
	if !safeSQLIdentifier.MatchString(identifier) {
		panic("unsafe SQL identifier")
	}
	return `"` + identifier + `"`
}
